# yaml-language-server: $schema=https://promptfoo.dev/config-schema.json
description: Variable rewriting with prompt optimizer - completely rewrite variable values to make tests pass

prompts:
  - 'Translate the following to French: {{text}}'

providers:
  - openai:gpt-4o

tests:
  # Test 1: Need to find English text that translates to something containing "bonjour"
  - provider:
      id: promptfoo:prompt-optimizer
      config:
        maxTurns: 3
        targetVariable: text
        improverModel: openai:gpt-4o
    vars:
      text: Hello world
    assert:
      - type: icontains
        value: bonjour

  # Test 2: Need to find English text that translates to something containing "matin" (morning)
  - provider:
      id: promptfoo:prompt-optimizer
      config:
        maxTurns: 3
        targetVariable: text
        improverModel: openai:gpt-4o
    vars:
      text: Good morning
    assert:
      - type: icontains
        value: matin

  # Test 3: Need to find English text that translates to something containing "merci" (thank you)
  - provider:
      id: promptfoo:prompt-optimizer
      config:
        maxTurns: 3
        targetVariable: text
        improverModel: openai:gpt-4o
    vars:
      text: Thank you very much
    assert:
      - type: icontains
        value: merci

  # Test 4: Challenge case - need text that translates to something containing "chat" (cat)
  - provider:
      id: promptfoo:prompt-optimizer
      config:
        maxTurns: 3
        targetVariable: text
        improverModel: openai:gpt-4o
    vars:
      text: I like animals
    assert:
      - type: icontains
        value: chat

  # Test 5: VERY challenging - need "nuit" (night) from a completely unrelated starting point
  - provider:
      id: promptfoo:prompt-optimizer
      config:
        maxTurns: 4
        targetVariable: text
        improverModel: openai:gpt-4o
    vars:
      text: The weather is nice today
    assert:
      - type: icontains
        value: nuit
