# yaml-language-server: $schema=https://promptfoo.dev/config-schema.json
description: OpenAI image generation comparison

prompts:
  - 'Generate an image showing {{image_prompt}}'

providers:
  - id: openai:image:gpt-image-1
    label: 'GPT Image 1'
    config:
      quality: 'medium'
      size: '1024x1024'
      output_format: 'png'
  - id: openai:image:dall-e-3
    label: 'DALL-E 3'
    config:
      quality: 'standard'
      size: '1024x1024'

tests:
  - vars:
      image_prompt: 'a futuristic conference room with developers coding'
  - vars:
      image_prompt: 'a serene mountain lake at sunset'
