# yaml-language-server: $schema=https://promptfoo.dev/config-schema.json
description: Multi-turn Image Generation and Conversation with OpenAI Responses API

prompts:
  - "{{message}}"

providers:
  - id: openai:responses:gpt-4.1-mini
    config:
      temperature: 0.7
      max_output_tokens: 1000
      tools:
        - type: image_generation
          size: 1024x1024
          quality: high
          background: transparent

tests:
  # Coffee shop conversation thread
  - vars:
      message: "Generate an image of a cozy coffee shop on a rainy day"
    metadata:
      conversationId: coffee_shop_thread
  - vars:
      message: "What's the mood and atmosphere of this coffee shop scene?"
    metadata:
      conversationId: coffee_shop_thread
  - vars:
      message: "What kind of people might visit this place? Describe the typical customers."
    metadata:
      conversationId: coffee_shop_thread
  - vars:
      message: "Can you generate a variation of this coffee shop with warmer, more golden lighting?"
    metadata:
      conversationId: coffee_shop_thread

  # Futuristic city conversation thread  
  - vars:
      message: "Create an image of a futuristic city skyline at sunset"
    metadata:
      conversationId: futuristic_city_thread
  - vars:
      message: "What technologies and architectural features do you see in this cityscape?"
    metadata:
      conversationId: futuristic_city_thread
  - vars:
      message: "How does this futuristic city compare to modern cities today?"
    metadata:
      conversationId: futuristic_city_thread
  - vars:
      message: "Generate a daytime version of this same futuristic city"
    metadata:
      conversationId: futuristic_city_thread

  # Magical forest conversation thread
  - vars:
      message: "Generate an image of a magical forest with glowing mushrooms and ethereal lighting"
    metadata:
      conversationId: magical_forest_thread
  - vars:
      message: "What creatures and magical beings might inhabit this enchanted forest?"
    metadata:
      conversationId: magical_forest_thread
  - vars:
      message: "Describe the lighting and atmosphere in detail - what makes it feel magical?"
    metadata:
      conversationId: magical_forest_thread
  - vars:
      message: "Create a darker, more mysterious version of this magical forest for nighttime"
    metadata:
      conversationId: magical_forest_thread 