# yaml-language-server: $schema=https://promptfoo.dev/config-schema.json
description: OpenAI Responses API with structured output and image generation

prompts:
  - 'Extract information about the event: {{event}}'
  - 'Generate an image showing {{image_prompt}}'

providers:
  - id: openai:responses:gpt-4.5-preview
    label: json-schema
    config:
      temperature: 0.7
      instructions: 'You are a helpful AI assistant. Extract key details about the event.'
      response_format:
        type: 'json_schema'
        name: 'event_information'
        schema:
          type: 'object'
          properties:
            event_name:
              type: 'string'
              description: 'The name of the event'
            date:
              type: 'string'
              description: 'When the event takes place'
            location:
              type: 'string'
              description: 'Where the event takes place'
            participants:
              type: 'array'
              items:
                type: 'string'
              description: 'People attending the event'
          required: ['event_name', 'date', 'location', 'participants']
          additionalProperties: false

  - id: openai:responses:gpt-4.1-mini
    label: image-generation
    config:
      tools:
        - type: image_generation
          quality: 'medium'
          size: '1024x1024'

tests:
  - vars:
      event: 'Alice and Bob are attending a JSON schema conference in New York on September 15th, 2025.'
  - vars:
      event: 'The annual music festival will take place in Central Park this weekend, featuring local artists and food vendors.'
  - vars:
      image_prompt: 'a futuristic conference room with developers coding'
