# yaml-language-server: $schema=https://promptfoo.dev/config-schema.json
description: Comparing DALL-E 2 and 3 image generation capabilities

prompts:
  - 'In the style of Van Gogh: {{subject}}'
  - 'In the style of Dali: {{subject}}'
  - 'Photorealistic image of {{subject}}'

providers:
  - id: openai:image:dall-e-3
    config:
      size: '1024x1024'
      quality: 'hd'
  - id: openai:image:dall-e-2
    config:
      size: '1024x1024'
  - id: openai:image:gpt-image-1
    config:
      size: '1024x1024'
      quality: 'medium'
      output_format: 'png'
  - id: openai:image:gpt-image-1
    label: 'GPT Image 1 (High Quality)'
    config:
      size: '1024x1536'
      quality: 'high'
      output_format: 'jpeg'
      output_compression: 85
  - id: openai:image:gpt-image-1
    label: 'GPT Image 1 (Transparent)'
    config:
      size: '1024x1024'
      quality: 'high'
      background: 'transparent'
      output_format: 'png'

tests:
  - vars:
      subject: bananas
  - vars:
      subject: new york city
  - vars:
      subject: robot playing chess
  - vars:
      subject: mountain landscape at sunset
