# yaml-language-server: $schema=https://promptfoo.dev/config-schema.json
description: Comparing OpenAI image generation models

prompts:
  - 'Create an image of {{subject}}'

providers:
  - id: openai:image:dall-e-3
    config:
      size: '1024x1024'
      quality: 'standard'
  - id: openai:image:gpt-image-1
    config:
      size: '1024x1024'
      quality: 'medium'

tests:
  - vars:
      subject: a cat wearing a hat
  - vars:
      subject: a mountain landscape at sunset
