# yaml-language-server: $schema=https://promptfoo.dev/config-schema.json

# Learn more about building a configuration: https://promptfoo.dev/docs/configuration/guide

description: 'Google AI Studio Tools demonstration'

prompts:
  - What is the weather in {{location}}?
  - "{{search_query}}"

providers:
  - id: 'google-function-calling'
    provider: 'google:gemini-2.0-flash-001'
    config:
      tools: file://tools.json

  - id: 'google-search-grounding'
    provider: 'google:gemini-2.0-flash'
    config:
      tools: file://search-tools.json

defaultTest:
  options:
    # This overrides the default grading providers with Vertex AI models
    providers:
      embedding: 'google:embedding:text-embedding-005'
      text: 'google:gemini-2.0-flash-001'

tests:
  # Function calling example - use first prompt
  - vars:
      location: San Francisco
    provider: google-function-calling
    assert:
      - type: is-valid-function-call
      - type: equals
        value: get_current_weather
        transform: output[0].functionCall.name
      - type: similar
        value: '{{location}}'
        threshold: 0.9
        transform: output[0].functionCall.args.location

  - vars:
      location: New York
    provider: google-function-calling
    assert:
      - type: is-valid-function-call
      - type: equals
        value: get_current_weather
        transform: output[0].functionCall.name
      - type: similar
        value: '{{location}}'
        threshold: 0.9
        transform: output[0].functionCall.args.location

  # Google Search examples - use second prompt
  - vars:
      search_query: What is the current Google stock price?
    prompt: 1
    provider: google-search-grounding
    assert:
      - type: contains
        value: stock
      - type: javascript
        value: "!!result.raw?.candidates?.[0]?.groundingMetadata"

  - vars:
      search_query: What are the latest developments in AI?
    prompt: 1
    provider: google-search-grounding
    assert:
      - type: contains
        value: AI
      - type: javascript
        value: "!!result.raw?.candidates?.[0]?.groundingMetadata"
