# yaml-language-server: $schema=https://promptfoo.dev/config-schema.json
description: 'Grok-3 Models Test Configuration'

prompts:
  - |
    Solve this math problem step by step:
    {{math_problem}}
  - |
    Summarize this text in one paragraph:
    {{text}}
  - |
    Write a technical analysis of this code:
    {{code}}

providers:
  # Grok-3 Mini with reasoning (for math problems)
  - id: xai:grok-3-mini-beta
    config:
      config:
        reasoning_effort: 'high' # Use high reasoning for complex problems
        temperature: 0.2 # Low temperature for more deterministic output
        max_tokens: 1000

  # Faster version of Grok-3 Mini with reasoning
  - id: xai:grok-3-mini-fast-beta
    config:
      config:
        reasoning_effort: 'low' # Use low reasoning for simpler problems
        temperature: 0.3
        max_tokens: 500

  # Standard Grok-3 for general tasks
  - id: xai:grok-3-beta
    config:
      config:
        temperature: 0.7
        max_tokens: 2000

  # Faster version of standard Grok-3
  - id: xai:grok-3-fast-beta
    config:
      config:
        temperature: 0.7
        max_tokens: 1000

tests:
  # Test reasoning capabilities with math problems
  - vars:
      math_problem: 'If a train travels at 60 mph for 2.5 hours, then increases speed to 75 mph for 1.5 hours, what is the total distance covered?'
    assert:
      - type: contains
        value: 'step' # Should show step-by-step reasoning
      - type: contains
        value: 'total distance'

  # Test summarization capabilities
  - vars:
      text: |
        The James Webb Space Telescope (JWST) is the largest and most powerful space telescope ever built. 
        Launched on December 25, 2021, it is an international program led by NASA with its partners, ESA and CSA. 
        The telescope is designed to study various phases of cosmic history, from within our solar system to the 
        most distant observable galaxies in the early universe. Unlike its predecessor, the Hubble Space Telescope, 
        JWST primarily observes in the infrared spectrum, allowing it to see through cosmic dust and gas that visible 
        light cannot penetrate.
    assert:
      - type: contains
        value: 'Webb'
      - type: contains
        value: 'telescope'

  # Test code analysis capabilities
  - vars:
      code: |
        def fibonacci(n):
            if n <= 1:
                return n
            else:
                a, b = 0, 1
                for _ in range(n-1):
                    a, b = b, a + b
                return b
    assert:
      - type: contains
        value: 'fibonacci'
      - type: contains
        value: 'algorithm'
# Optional: Configure region-specific endpoint
# Uncomment and set your region if needed
# defaultTest:
#   options:
#     provider:
#       config:
#         config:
#           region: us-west-1
