# yaml-language-server: $schema=https://promptfoo.dev/config-schema.json
description: OpenAI Deep Research with Web Search
prompts:
  - |
    Research {{topic}} and provide a summary of what you find.

providers:
  - id: openai:responses:o4-mini-deep-research
    config:
      max_output_tokens: 20000
      tools:
        - type: web_search_preview

tests:
  - vars:
      topic: "Python programming language"
    assert:
      - type: contains-any
        value: ['Python', 'programming', 'language', 'code', 'development']
      - type: llm-rubric
        value: 'Response should provide information about Python programming language. Should be informative and demonstrate research capabilities.'
      - type: is-json
        value: false 