# yaml-language-server: $schema=https://promptfoo.dev/config-schema.json
description: OpenAI Responses API demonstration
prompts:
  - Tell me about {{topic}}
providers:
  - id: openai:responses:gpt-4o
    config:
      max_output_tokens: 4000
tests:
  - vars:
      topic: machine learning
    assert:
      - type: contains-any
        value: [machine learning, ML, algorithms, data]
  - vars:
      topic: space exploration
    assert:
      - type: contains-any
        value: [space, NASA, rocket, planet, astronomy]
