# yaml-language-server: $schema=https://promptfoo.dev/config-schema.json
description: GPT Image 1 Generation Examples

prompts:
  - 'Create an image of {{scene}}'
  - 'Generate a high-quality image showing {{scene}} with {{style}} style'

providers:
  - id: openai:image:gpt-image-1
    label: 'GPT Image 1 (Medium Quality)'
    config:
      size: '1024x1024'
      quality: 'medium'
      output_format: 'png'

  - id: openai:image:gpt-image-1
    label: 'GPT Image 1 (High Quality)'
    config:
      size: '1024x1536'
      quality: 'high'
      output_format: 'jpeg'
      output_compression: 85

  - id: openai:image:gpt-image-1
    label: 'GPT Image 1 (Transparent)'
    config:
      size: '1024x1024'
      quality: 'high'
      background: 'transparent'
      output_format: 'png'

  - id: openai:image:gpt-image-1
    label: 'GPT Image 1 (Auto Settings)'
    config:
      quality: 'auto'
      size: 'auto'
      moderation: 'low'

tests:
  - description: 'Nature scene'
    vars:
      scene: 'a serene mountain lake at sunset'
      style: 'photorealistic'

  - description: 'Fantasy scene'
    vars:
      scene: 'a magical forest with glowing mushrooms'
      style: 'fantasy art'

  - description: 'Portrait scene'
    vars:
      scene: 'a wise old wizard with a long beard'
      style: 'detailed portrait'
