# yaml-language-server: $schema=https://promptfoo.dev/config-schema.json
description: GPT Image 1 Generation Examples

prompts:
  - 'Create an image of {{scene}}'
  - 'Generate a high-quality image showing {{scene}} with {{style}} style'
  - 'Make an artistic image of {{scene}} with {{background}} background'

providers:
  # Basic GPT Image 1 with standard settings
  - id: openai:image:gpt-image-1
    label: 'Basic GPT Image 1'
    config:
      size: '1024x1024'
      quality: 'medium'
      output_format: 'png'

  # High-quality with transparency
  - id: openai:image:gpt-image-1
    label: 'High Quality with Transparency'
    config:
      size: '1024x1536'
      quality: 'high'
      output_format: 'png'
      background: 'transparent'
      output_compression: 90

  # WebP format for smaller file sizes
  - id: openai:image:gpt-image-1
    label: 'WebP Compressed'
    config:
      size: '1536x1024'
      quality: 'auto'
      output_format: 'webp'
      output_compression: 75

tests:
  # Simple scenes
  - description: 'Nature scene'
    vars:
      scene: 'a serene mountain lake at sunset with pine trees reflected in the water'
      style: 'photorealistic'
      background: 'natural'

  - description: 'Urban scene'
    vars:
      scene: 'a bustling city street with cafes and pedestrians'
      style: 'vibrant and modern'
      background: 'urban'

  - description: 'Fantasy scene'
    vars:
      scene: 'a magical forest with glowing mushrooms and fairy lights'
      style: 'fantasy art'
      background: 'enchanted'

  # Test with transparency
  - description: 'Logo-style with transparency'
    vars:
      scene: 'a minimalist geometric logo design'
      style: 'clean and modern'
      background: 'transparent'

  # Test different formats
  - description: 'Artistic portrait'
    vars:
      scene: 'a portrait of a wise old wizard with a long beard'
      style: 'oil painting'
      background: 'dark' 