# yaml-language-server: $schema=https://promptfoo.dev/config-schema.json
description: Fact Checking with Research Rubric

prompts:
  - 'Answer this question with specific facts and statistics: {{question}}'

providers:
  - id: openai:responses:gpt-4o
    config:
      temperature: 0.5
      max_output_tokens: 300
      tools:
        - type: web_search

  - id: google:gemini-2.5-flash
    config:
      temperature: 0.5
      maxOutputTokens: 300
      tools:
        - googleSearch: {}

  - id: xai:grok-3-beta
    config:
      temperature: 0.5
      max_tokens: 300
      search_parameters:
        mode: 'on'
        return_citations: true

tests:
  - vars:
      question: What is the current population of Tokyo, Japan?
    assert:
      - type: research-rubric
        value: |
          Verify that the population figure provided is accurate and current 
          (within the last 2 years). The source of the data should be credible.

  - vars:
      question: Who won the Nobel Prize in Physics in 2023?
    assert:
      - type: research-rubric
        value: |
          Verify the winners' names and their research topic. All information 
          should match official Nobel Prize announcements.

  - vars:
      question: What is the GDP of France in 2023?
    assert:
      - type: research-rubric
        value: |
          The GDP figure should be verifiable from official sources like the 
          World Bank, IMF, or French government statistics. Accept values in 
          both nominal and PPP terms if properly labeled.

  - vars:
      question: When was the James Webb Space Telescope launched?
    assert:
      - type: research-rubric
        value: |
          The launch date should be December 25, 2021. Any other date is 
          incorrect. Additional details about the launch location or vehicle 
          should also be accurate if provided.
