# yaml-language-server: $schema=https://promptfoo.dev/config-schema.json
description: AWS Bedrock Knowledge Base RAG

prompts:
  - 'Please answer the following questions based on the provided knowledge base: {{prompt}}'

providers:
  # Knowledge Base provider with explicit config
  - id: bedrock:kb:anthropic.claude-v2:1
    config:
      knowledgeBaseId: '0VMCLLCVGB'
      region: 'us-east-2'
      numberOfResults: 5
      temperature: 0.0
      maxTokens: 1000
  
  # Regular provider for comparison
  - id: bedrock:anthropic.claude-3-7-sonnet-20250219-v1:0
    config:
      region: 'us-east-2'

tests:
  - vars:
      prompt: 'What is promptfoo and what problem does it solve?'
  - vars:
      prompt: 'How do I evaluate prompts with promptfoo?'
  - vars:
      prompt: 'What providers and models does promptfoo support?'
  - vars:
      prompt: 'How can I use assertions in promptfoo to test responses?'
  - vars:
      prompt: 'What are some advanced features of promptfoo for enterprise users?'
