description: Example of using Microsoft Prompty files with promptfoo

prompts:
  - file://customer_service.prompty
  - file://technical_support.prompty
  - file://completion_example.prompty

providers:
  - openai:gpt-3.5-turbo
  - openai:gpt-4

tests:
  - vars:
      customerName: Sarah
      issue: My subscription expired but I was still charged
      company: TechStart Inc
  
  - vars:
      product: DataSync Enterprise
      error: "Connection refused: Unable to reach server"
      platform: Ubuntu 22.04
    assert:
      - type: contains
        value: troubleshoot
  
  - vars:
      beginning: In the year 2150, humanity discovered
    assert:
      - type: llm-rubric
        value: The completion should be creative and continue the sci-fi theme 