# yaml-language-server: $schema=https://promptfoo.dev/config-schema.json
description: Testing OpenAI Assistants API capabilities
env:
  OPENAI_API_KEY: $OPENAI_API_KEY

prompts:
  - file://prompts/basic_instructions.txt
  - file://prompts/function_instructions.txt
  - file://prompts/advanced_instructions.txt

providers:
  - id: openai:assistant:asst_CCDJc0V4MoAZ5WGEmtozI3bt
    config:
      tools:
        - type: function
          function:
            name: get_weather
            description: Get the current weather in a given location
            parameters:
              type: object
              properties:
                location:
                  type: string
                  description: The city and state, e.g., San Francisco, CA
                unit:
                  type: string
                  enum: ["celsius", "fahrenheit"]
                  description: The unit of temperature
              required: ["location"]

tests:
  - vars:
      query: What's the weather like in San Francisco?
      prompt: 0
    assert:
      - type: non-empty
        value: true

  - vars:
      query: Tell me a joke about programming
      prompt: 0
    assert:
      - type: contains
        value: program
      - type: llm-rubric
        value: Is this response humorous and related to programming? Score 1-10

  - vars:
      query: Get the weather in New York with temperature in celsius
      prompt: 1
    assert:
      - type: javascript
        value: |
          return output.includes('function') || output.includes('tool')
            ? 'pass'
            : 'Function calling not detected';
      - type: javascript
        value: |
          return output.includes('New York') && output.includes('celsius')
            ? 'pass'
            : 'Location or temperature unit not correctly processed';

  - vars:
      query: Explain quantum computing in simple terms
      prompt: 2
    assert:
      - type: llm-rubric
        value: Does this explanation of quantum computing use simple language a non-expert could understand? Score 1-10
      - type: similar
        value: Quantum computing uses quantum bits or qubits
        threshold: 0.6 
