# yaml-language-server: $schema=https://promptfoo.dev/config-schema.json
description: 'AWS Bedrock Knowledge Base RAG Example'

prompts:
  - 'What is the capital of France?'
  - 'Who wrote the book "1984"?'
  - 'What were the major events of World War II?'
  - 'How does photosynthesis work?'
  - 'Tell me about quantum computing.'

providers:
  - id: bedrock:kb:anthropic.claude-3-sonnet-20240229-v1:0
    config:
      region: 'us-east-1'
      knowledgeBaseId: 'YOUR_KNOWLEDGE_BASE_ID'
      # Optional: You can specify your own modelArn if needed
      # modelArn: 'arn:aws:bedrock:us-east-1::foundation-model/anthropic.claude-3-sonnet-20240229-v1:0'
      # Optional: AWS credentials (if not using environment variables or IAM role)
      # accessKeyId: 'YOUR_ACCESS_KEY_ID'
      # secretAccessKey: 'YOUR_SECRET_ACCESS_KEY'

tests:
  - description: 'Basic factual questions from the knowledge base'
#
# To run this example:
# 1. Create a Knowledge Base in AWS Bedrock
# 2. Replace YOUR_KNOWLEDGE_BASE_ID with your actual Knowledge Base ID
# 3. Run: promptfoo eval -c examples/amazon-bedrock/promptfooconfig.knowledge-base.yaml
#
# Note: Ensure you have installed the required SDK:
# npm install -g @aws-sdk/client-bedrock-agent-runtime
#
