# yaml-language-server: $schema=https://promptfoo.dev/config-schema.json
description: Evaluating Langflow visual AI workflows

prompts:
  - "{{query}}"

providers:
  - file://langflow_provider.py
  - openai:gpt-4o-mini

tests:
  - vars:
      query: "Hello! How can you help me today?"
    assert:
      - type: contains
        value: help
      - type: javascript
        value: output.length > 10

  - vars:
      query: "What is artificial intelligence?"
    assert:
      - type: contains-any
        value:
          - "AI"
          - "artificial intelligence"
          - "machine learning"
          - "intelligence"
      - type: llm-rubric
        value: Response provides a clear explanation of AI

  - vars:
      query: "Write a simple Python function to add two numbers"
    assert:
      - type: contains-any
        value:
          - "def"
          - "function"
          - "python"
          - "+"
      - type: llm-rubric
        value: Response includes working Python code

  - vars:
      query: "What's 2 + 2?"
    assert:
      - type: contains
        value: "4"

  - vars:
      query: ""
    assert:
      - type: llm-rubric
        value: Handles empty input gracefully without errors
