# yaml-language-server: $schema=https://promptfoo.dev/config-schema.json
description: OpenAI GPT Image model evaluation
prompts:
  - 'Create a detailed {{style}} illustration of {{subject}}'

providers:
  - id: openai:image:gpt-image-1
    config:
      output_format: 'webp'
      moderation: 'low' # Less restrictive filtering

tests:
  - vars:
      style: hyperrealistic oil painting with subtle dreamlike atmosphere
      subject: the Golden Gate Bridge at sunset with fog rolling in
  - vars:
      style: photorealistic documentary photography with surreal color grading
      subject: the first Apple computer being unveiled at the Homebrew Computer Club in 1976
  - vars:
      style: hyperrealistic watercolor with floating geometric elements
      subject: Times Square during the 1969 moon landing celebration
  - vars:
      style: photorealistic architectural visualization with impossible lighting
      subject: the original ENIAC computer room at the University of Pennsylvania
  - vars:
      style: hyperrealistic technical illustration with floating equations
      subject: the Apollo 11 lunar module with labeled components
  - vars:
      style: photorealistic noir with surreal shadows
      subject: Alan Turing breaking the Enigma code at Bletchley Park
