# yaml-language-server: $schema=https://promptfoo.dev/config-schema.json
prompts:
  - 'In the style of {{artist}}: {{subject}}'

providers:
  - id: openai:image:dall-e-3
    config:
      size: 1024x1024 # Valid sizes for DALL-E 3: 1024x1024, 1792x1024, 1024x1792

  - id: openai:image:dall-e-2
    config:
      size: 512x512 # Valid sizes for DALL-E 2: 256x256, 512x512, 1024x1024
      # response_format: b64_json # Returns the raw JSON response with base64-encoded image data

  # New GPT Image 1 model with advanced features
  - id: openai:image:gpt-image-1
    config:
      size: 1024x1024 # Valid sizes for GPT Image 1: 1024x1024, 1536x1024, 1024x1536, auto
      quality: high # Valid qualities: low, medium, high, auto
      background: transparent # Valid backgrounds: transparent, opaque, auto
      format: png # Valid formats: png, jpeg, webp
      # output_compression: 80 # For JPEG/WebP: 0-100
      # moderation: auto # Valid values: auto, low

  # GPT Image 1 via Responses API with image generation tool
  - id: openai:responses:gpt-4.1-mini
    config:
      tools:
        - type: image_generation
          size: 1024x1024
          quality: high
          background: transparent

tests:
  - vars:
      artist: Van Gogh
      subject: sunset over mountains
  - vars:
      artist: Dali
      subject: melting clocks
  - vars:
      artist: Picasso
      subject: abstract faces
  - vars:
      artist: Monet
      subject: water lilies
  - vars:
      artist: Warhol
      subject: colorful soup cans
