# yaml-language-server: $schema=https://promptfoo.dev/config-schema.json
description: Evaluating PydanticAI agents with structured outputs

# Enable tracing for OpenTelemetry
tracing:
  enabled: true
  otlp:
    http:
      enabled: true
      port: 4318

prompts:
  - "{{query}}"

providers:
  - id: pydantic-ai-agent
    python: pydantic_ai_provider.py

tests:
  - vars:
      query: "I need help with my account login"
    assert:
      - type: contains
        value: "Category: support"
      - type: llm-rubric
        value: "The response should be helpful and address the login issue"

  - vars:
      query: "I want to cancel my subscription"
    assert:
      - type: contains
        value: "billing"
      - type: llm-rubric
        value: "The response should acknowledge the cancellation request"

  - vars:
      query: "Your service is terrible and I'm very upset!"
    assert:
      - type: contains
        value: "Sentiment: negative"
      - type: contains
        value: "Needs Escalation: true"
      - type: llm-rubric
        value: "The response should be empathetic and professional"

  - vars:
      query: "How do I update my shipping address?"
    assert:
      - type: contains
        value: "Category: support"
      - type: llm-rubric
        value: "The response should provide clear instructions"
