# yaml-language-server: $schema=https://promptfoo.dev/config-schema.json
description: 'Demonstrate Claude thinking feature for step-by-step problem solving'

prompts:
  - '{{question}}'

providers:
  - id: anthropic:messages:claude-3-7-sonnet-20250219
    config:
      max_tokens: 8192 # Must be greater than budget_tokens
      thinking:
        type: 'enabled'
        budget_tokens: 4096
  # AWS Bedrock (requires model access to be enabled in your AWS account)
  - id: bedrock:us.anthropic.claude-3-7-sonnet-20250219-v1:0
    config:
      max_tokens: 8192 # Must be greater than budget_tokens
      thinking:
        type: 'enabled'
        budget_tokens: 4096
      region: us-west-2

# Basic verification that thinking is present
defaultTest:
  assert:
    - type: javascript
      value: |
        return output.includes('Thinking:') ? 'pass' : 'fail: No thinking section found';

tests:
  - vars:
      question: |
        You have 8 identical balls, but one is slightly heavier than the others. 
        Using a balance scale, what is the minimum number of weighings needed to 
        find the heavier ball?
    assert:
      - type: llm-rubric
        value: |
          Evaluate the reasoning quality on a scale of 1-5:
          1. Did the response identify that 2 weighings are sufficient?
          2. Did the thinking section show a clear step-by-step approach?
          3. Was the final answer correct (2 weighings)?

  - vars:
      question: |
        A train leaves Boston at 8:00 AM traveling west at 100 mph. Another train 
        leaves Chicago at 10:00 AM traveling east at 120 mph. If the distance 
        between Boston and Chicago is 1000 miles, at what time will the trains meet?
    assert:
      - type: llm-rubric
        value: |
          Evaluate if the trains meet at approximately 1:38 PM.
