# yaml-language-server: $schema=https://promptfoo.dev/config-schema.json
description: Python OpenTelemetry tracing example

prompts:
  - 'Research the topic: {{topic}}'

providers:
  - id: python:provider.py

tests:
  - vars:
      topic: quantum computing advances
    assert:
      - type: contains
        value: 'Executive Summary'

  - vars:
      topic: renewable energy breakthroughs
    assert:
      - type: contains
        value: 'Main Points'

  - vars:
      topic: artificial intelligence safety
    assert:
      - type: contains
        value: 'Conclusion'

# Enable tracing to see the multi-agent workflow
# Note: Python OTLP exporter sends protobuf format which may not display properly
tracing:
  enabled: true
  otlp:
    http:
      enabled: true
      port: 4318
      acceptFormats: ['json']
