# yaml-language-server: $schema=https://promptfoo.dev/config-schema.json
description: ADK tracing with real LLM calls

prompts:
  - 'Research the latest developments in {{topic}} and provide a summary with fact-checked information'

providers:
  - id: file://provider-with-llm.js
    label: adk-with-openai
    config:
      model: gpt-4o-mini

defaultTest:
  assert:
    # Content validation
    - type: contains
      value: 'Executive Summary'
    
    # Ensure LLM calls were made
    - type: trace-span-count
      value:
        pattern: 'openai.chat.completion'
        min: 2  # At least analysis and summary

tests:
  - vars:
      topic: 'how dolphins use echolocation to order pizza'
    assert:
      - type: javascript
        value: |
          // Check for creative response about dolphins
          const hasOcean = output.toLowerCase().includes('ocean') || 
                          output.toLowerCase().includes('marine') ||
                          output.toLowerCase().includes('dolphin');
          return hasOcean ? { pass: true, reason: 'Found ocean-related content' } : 
                           { pass: false, reason: 'Missing marine context' };

  - vars:
      topic: 'why penguins would make excellent software engineers'
    assert:
      - type: llm-rubric
        value: |
          Does the response creatively explain why penguins would be good at coding?
          Consider mentions of: teamwork, problem-solving, persistence, or debugging.
          Score 1 if creative and plausible, 0 if too serious or off-topic.

  - vars:
      topic: 'the secret underground society of sentient houseplants'
    assert:
      - type: contains-any
        value: ['plant', 'photosynthesis', 'secret', 'society']
      
      # Verify all agents participated
      - type: trace-span-count
        value:
          pattern: '*_agent.process'
          min: 3

# Enable tracing (this goes at the end per promptfoo conventions)
tracing:
  enabled: true
  otlp:
    http:
      enabled: true
      port: 4318
      acceptFormats: ['json'] 