# yaml-language-server: $schema=https://promptfoo.dev/config-schema.json
description: Extension Hook Example

prompts:
  - 'Rephrase this in {{language}}: {{body}}'

providers:
  - file://customOpenAIApiProvider.js

extensions:
  - file://hooks.py:extension_hook
  # - file://hooks.js:extensionHook

defaultTest:
  assert:
    - type: is-json
      value:
        required:
          - content
          - metadata
        type: object
    - type: contains
      value: 'pf-trace-494949'

tests:
  - vars:
      body: 'Hello, how are you?'
      language: 'Norwegian'
    assert:
      - type: contains-any
        value:
          - 'Hallo'
          - 'Hei'
          - 'Hå'
      - type: not-contains
        value: 'Hello'
  - vars:
      body: 'I love sailing on the sea.'
      language: 'French'
    assert:
      - type: llm-rubric
        value: 'The response is in French'
