# yaml-language-server: $schema=https://promptfoo.dev/config-schema.json
description: Llama 3.2 multimodal evaluation with Amazon Bedrock

prompts:
  - file://prompts/image_prompt.txt

providers:
  - id: bedrock:us.meta.llama3-2-90b-instruct-v1:0
    label: Llama 3.2 90B
    config:
      region: us-west-2

tests:
  - vars:
      image_path: images/cat.jpg
      question: What is in this image? Describe it in detail.
    assert:
      - type: contains
        value: cat
  - vars:
      image_path: images/dog.jpg
      question: What type of animal is shown in this image?
  - vars:
      image_path: images/landscape.jpg
      question: Describe this scene in detail.
