# yaml-language-server: $schema=https://promptfoo.dev/config-schema.json

prompts:
  - |
    Given this math puzzle: {{puzzle}}
    Please solve this step by step, showing your reasoning process.
  - |
    {{search_query}}

providers:
  - id: google:gemini-2.5-flash-preview-04-17
    config:
      generationConfig:
        temperature: 0.7
        maxOutputTokens: 2048
        thinkingConfig:
          thinkingBudget: 1024

  - google:gemini-2.0-flash-exp

  - google:gemini-2.0-flash-thinking-exp

  - id: google:gemini-2.5-pro-exp-03-25
    config:
      temperature: 0.7
      maxOutputTokens: 2048

  - id: google:gemini-1.5-pro
    config:
      temperature: 0.7
      maxOutputTokens: 1024
      topP: 0.9
      topK: 40

  # Google Search grounding example with Gemini 2.0
  - id: google:gemini-2.0-flash
    config:
      temperature: 0.2
      maxOutputTokens: 1024
      tools:
        - google_search: {}

  # Google Search retrieval example with Gemini 1.5
  - id: google:gemini-1.5-flash
    config:
      temperature: 0.2
      maxOutputTokens: 1024
      tools:
        - google_search_retrieval:
            dynamic_retrieval_config:
              mode: "MODE_DYNAMIC"
              dynamic_threshold: 0.3

  # Structured output example
  - id: google:gemini-1.5-pro
    config:
      generationConfig:
        temperature: 0
        maxOutputTokens: 1024
        response_mime_type: 'application/json'
        response_schema:
          type: 'object'
          properties:
            answer:
              type: 'string'
              description: 'The numerical or text answer'
            confidence:
              type: 'string'
              enum: ['high', 'medium', 'low']
            method_used:
              type: 'string'
              description: 'One-word description of solving method'
          required: ['answer', 'confidence', 'method_used']

  # Function calling example
  - id: google:gemini-1.5-pro
    config:
      tools:
        function_declarations:
          - name: 'verify_answer'
            description: 'Verify if the answer is correct'
            parameters:
              type: 'object'
              properties:
                answer:
                  type: 'string'
                  description: 'The proposed answer'
                explanation:
                  type: 'string'
                  description: 'Brief explanation'
              required: ['answer']
      tool_config:
        function_calling_config:
          mode: 'auto'

tests:
  - vars:
      puzzle: 'If a train travels at 60 mph for 2.5 hours, then at 40 mph for 1.5 hours, what is the average speed for the entire journey?'
    assert:
      - type: contains
        value: 52.5
      - type: llm-rubric
        value: |
          The answer should be 52.5 mph.

  # Test for search grounding
  - vars:
      search_query: What is the current Google stock price?
    assert:
      - type: contains
        value: stock
      - type: json-contains
        value:
          candidates:
            - groundingMetadata:
                webSearchQueries: []
        transform: raw
      - type: javascript
        value: "!!result.raw.candidates[0].groundingMetadata && !!result.raw.candidates[0].groundingMetadata.webSearchQueries"
