# yaml-language-server: $schema=https://promptfoo.dev/config-schema.json

description: 'Testing Gemini models with thinking capabilities'

prompts:
  - |
    Given this math puzzle: {{puzzle}}
    Provide a short, clear answer with minimal explanation.

providers:
  - google:gemini-2.0-flash-exp
  - google:gemini-2.0-flash-thinking-exp

  # Gemini 2.5 Pro with default thinking
  - id: google:gemini-2.5-pro-exp-03-25
    config:
      temperature: 0.7
      maxOutputTokens: 512

  # Using Gemini 1.5 Pro with default settings
  # Note: For Gemini 2.5 Flash, use the configuration below when the API is stable
  # id: google:gemini-2.5-flash-preview-04-17
  # config:
  #   temperature: 0.7
  #   maxOutputTokens: 1024
  #   apiVersion: v1
  #   thinkingConfig:
  #     thinkingBudget: 1024 # Control amount of reasoning (0-24576 tokens)
  #   topP: 0.9
  #   topK: 40
  - id: google:gemini-1.5-pro
    config:
      temperature: 0.7
      maxOutputTokens: 1024
      topP: 0.9
      topK: 40

  # Structured output example
  - id: google:gemini-1.5-pro
    config:
      generationConfig:
        temperature: 0
        maxOutputTokens: 1024
        response_mime_type: 'application/json'
        response_schema:
          type: 'object'
          properties:
            answer:
              type: 'string'
              description: 'The numerical or text answer'
            confidence:
              type: 'string'
              enum: ['high', 'medium', 'low']
            method_used:
              type: 'string'
              description: 'One-word description of solving method'
          required: ['answer', 'confidence', 'method_used']

  # Function calling example
  - id: google:gemini-1.5-pro
    config:
      tools:
        function_declarations:
          - name: 'verify_answer'
            description: 'Verify if the answer is correct'
            parameters:
              type: 'object'
              properties:
                answer:
                  type: 'string'
                  description: 'The proposed answer'
                explanation:
                  type: 'string'
                  description: 'Brief explanation'
              required: ['answer']
      tool_config:
        function_calling_config:
          mode: 'auto'

tests:
  - vars:
      puzzle: 'If a train travels at 60 mph for 2.5 hours, then at 40 mph for 1.5 hours, what is the average speed for the entire journey?'
    assert:
      - type: contains
        value: 52.5
      - type: llm-rubric
        value: |
          The answer should be 52.5 mph.

  - vars:
      puzzle: 'A rectangular garden has a perimeter of 120 feet and an area of 864 square feet. What are the dimensions of the garden?'
    assert:
      - type: contains
        value: 36
      - type: contains
        value: 24
      - type: llm-rubric
        value: |
          The garden dimensions should be 36 feet by 24 feet.
